swri-robotics/bag-database

README.md
The previous example wouldn't create a persistent database, which probably would've really annoyed people who were just copy/pasting the examples after the next time they recreated their Postgres container.
=> Adding a -v flag to the PostgreSQL Docker example.

CHANGELOG.md, pom.xml, src/main/java/com/github/swrirobotics/bags/persistence/SpringSessionAttribute.java
Updating to the latest bag reader library to add support for LZ4-compressed bag files.
Also removing a TODO that I forgot to remove in the previous commit.
=> LZ4 compression support

CHANGELOG.md, src/main/webapp/resources/js/application.js, src/main/webapp/resources/js/views/BagTreeFilterPanel.js, src/main/webapp/resources/js/views/SearchPanel.js
This uses HTML5 local storage to save the following:
- Selected tab
- Text in search boxes
- Checked search boxes
- Column visibility, order, and sorting
Resolves #38
=> Preserving widget states between reloads

CHANGELOG.md, pom.xml, src/main/java/com/github/swrirobotics/bags/BagService.java, src/main/java/com/github/swrirobotics/bags/filesystem/BagScanner.java, src/main/java/com/github/swrirobotics/bags/persistence/Bag.java, src/main/java/com/github/swrirobotics/bags/persistence/BagPosition.java, src/main/java/com/github/swrirobotics/bags/persistence/MessageType.java, src/main/java/com/github/swrirobotics/bags/persistence/Tag.java, src/main/java/com/github/swrirobotics/bags/persistence/Topic.java, src/main/java/com/github/swrirobotics/config/ConfigService.java, src/main/java/com/github/swrirobotics/support/web/Configuration.java, src/main/resources/db/changelog/db.changelog-1.4.yaml, src/main/resources/db/changelog/db.changelog-master.yaml, src/main/webapp/resources/js/views/ConfigWindow.js, src/test/java/com/github/swrirobotics/bags/persistence/BagRepositoryTest.java
This adds a new config value, "removeOnDeletion", that will cause the bag DB
to remove entries from the database if the associated files disappeared from
the filesystem.  This will be set to true by default.
It also makes a few tweaks to the database schema so that foreign keys associated with the `bags` table all have "ON DELETE CASCADE" set on them, so that when bags are removed, the database will remove related rows; this is much faster than using Hibernate to delete them manually.
Resolves #49
=> Add ability to remove bags from DB when deleted from filesystem

src/main/docker/entrypoint.sh, src/main/java/com/github/swrirobotics/bags/BagService.java, src/main/java/com/github/swrirobotics/support/web/Configuration.java
This can be used on lower spec machines or to allow multiple users to
access video streams.
The main difference is: we scale down the output video stream to a width of 400 (we maintain the aspect ratio), we change the crf parameter to 28 reducing the quality, and finally we reduce the output framerate to 24. 
The main assumption is that the database is not used for high-resolution video viewing but rather quick scans of the content.
Also, we limit the number of threads to 16 (ffmpeg issues warnings when using more than 16 explaining that it is not recommended to go over this number).
=> Add faster codec option

CHANGELOG.md, pom.xml
An issue when decompressing LZ4-compressed data chunks could cause
it to not work properly, so it would not be possible to view
images or movies from LZ4-compressed bags.
=> Fix LZ4 decompression

CHANGELOG.md, src/main/resources/db/changelog/db.changelog-1.8.yaml, src/main/resources/db/changelog/db.changelog-master.yaml
On newer versions of Postgres, the "attribute_bytes" column of the
"spring_session_attributes" table was being created with the type "oid",
but it should be "bytea".  This will detect if the column was created
with the wrong type and change it if necessary.
=> Fix wrong column type being used on Postgres

CHANGELOG.md, pom.xml, src/main/java/com/github/swrirobotics/bags/BagService.java
Manually setting metadata would fail for bag files that did not have
any GPS coordinates.
Fixes #81
=> Fix setting bag metadata

src/main/webapp/resources/js/views/BagTreePanel.js
Despite commit [29bef13f17](https://github.com/swri-robotics/bag-database/commit/29bef13f17a1417e10828408035ffd09bbdec047), the _Copy Link_ bug is still present in Folder View.  This pull request fixes it.
=> fix for "Copy Link" bug  in Folder view (still present)

CHANGELOG.md, Dockerfile, pom.xml, src/main/webapp/resources/js/views/AboutWindow.js
The Docker image being built did not have perl in it, which was causing
it to fail to parse lists of GPS coordinates, metadata, and vehicle name
topics from the environment when starting a new container
Fixes #82
Fixes #98
=> Add perl in Dockerfile

docs/installation/docker/behind-a-reverse-proxy.md, docs/installation/docker/with-ldap-authentication.md, docs/installation/docker/without-authentication.md, docs/installation/upgrading.md
The examples referred to an organization named "swri-robotics", but
actually "swrirobotics" is correct.
Fixes #119
=> Fix path to image in Docker examples

docs/scripts/scripts.md, src/main/java/com/github/swrirobotics/scripts/RunnableScript.java, src/main/java/com/github/swrirobotics/status/StatusService.java
The code that parsed Docker image names was incorrectly parsing ports
for custom Docker registries; this fixes that.
Also added a note indicating that authenticating with registries is
currently unsupported.
Signed-off-by: P. J. Reed <preed@swri.org>
=> Handle alternative Docker registries

src/main/java/com/github/swrirobotics/scripts/RunnableScript.java
If multiple bags were in different paths but had the same filename, they
would all be mounted at the same point inside the Docker container used
to run scripts, making it so that only one of them could actually be processed.
This adds the full path to the bag to its mount point to ensure it is unique.
Fixed #130
Signed-off-by: P. J. Reed <preed@swri.org>
=> Fix running scripts w/ multiple bags with the same name

src/main/java/com/github/swrirobotics/config/WebAppInitializer.java, src/main/webapp/resources/js/views/BagUploadWindow.js
The maximum upload size was set to 4GB, which is smaller than many bag files, so this increases the maximum to 50GB.  It also displays a more useful error message in the upload box if the size is exceeded.
Fixes #134
=> Increase max upload size to 50GB

src/main/java/com/github/swrirobotics/bags/BagService.java, src/main/java/com/github/swrirobotics/config/WebMvcConfig.java
Spring was killing async tasks that ran longer than 30 seconds, which was preventing users from streaming long videos.  This extends the timeout to 1 hour.
Fixes #153.
=> Extend async task timeout

CHANGELOG.md, pom.xml, src/main/java/com/github/swrirobotics/bags/storage/BagScanner.java, src/main/java/com/github/swrirobotics/bags/storage/filesystem/FilesystemBagStorageImpl.java, src/main/java/com/github/swrirobotics/bags/storage/s3/S3BagStorageImpl.java, src/main/java/com/github/swrirobotics/persistence/Bag.java, src/main/resources/db/changelog/db.changelog-2.3.yaml, src/main/resources/db/changelog/db.changelog-master.yaml, src/main/webapp/resources/js/views/AboutWindow.js
When the bag updater was scanning for new bags, if it encountered an exception while scanning, that can cause the entire operation to abort and not update or add any bags.
That's not necessarily a bad thing -- we don't want the database to end up in a bad state if it encounters some broken data -- but there were two particular exceptions causing it to stop that should be handled better.
First, this MR increases the maximum length of bag names to 255 characters, which is the maximum length allowed by most Linux filesystems.  It will also truncate files with longer names down to 255 characters.  This will stop it from throwing an exception for bags with long names.
Second, after updating is done, it attempts to remove bag files that are missing on the filesystem from the database.  If this …
=> Bag updater would stop working due to exceptions

docs/about.md, docs/installation/docker/behind-a-reverse-proxy.md, docs/installation/docker/with-a-private-registry.md, docs/installation/docker/with-ldap-authentication.md, docs/installation/docker/without-authentication.md, docs/installation/docker/without-compose.md, docs/installation/upgrading.md
Changes references in documentation from old Docker Hub registry location to new ghcr.io location.
=> Update Documentation to Reference New Registry Location

CHANGELOG.md, pom.xml, src/main/java/com/github/swrirobotics/config/SecurityConfig.java
Spring was trying to load LDAP-related beans even if no LDAP configuration
had been set, which would result in them throwing exceptions and shutting
everything down.
This marks the beans as @Lazy so they won't get initialized until the first
time they're used, which won't happen if there is no LDAP configuration.
I also went ahead and updated liquibase to 4.4.0 and tested it, and that
seems to work fine, so I'm including that, too.
Signed-off-by: P. J. Reed <phillipreed@hatchbed.com>
=> Update liquibase & fix ldap bean loading

pom.xml, src/main/java/com/github/swrirobotics/bags/BagService.java, src/test/java/com/github/swrirobotics/bags/BagControllerTest.java, src/test/java/com/github/swrirobotics/bags/BagServiceTest.java
If the bag database was unable to parse the metadata in a bag file, it would throw an exception and cause it to completely fail to read the bag file.  This change will make it log an error but continue processing the file.  It also switches to a newer version of the `bag-reader-java` library that will allow for creating mock `BagFile` objects for the purpose of unit tests.
Signed-off-by: P. J. Reed <phillipreed@hatchbed.com>
=> Handle invalid metadata in bag files

docker/ldap_authentication/docker-compose.yml, docker/private_registry/docker-compose.yml, docker/reverse_proxy/docker-compose.yml, docs/_config.yml, docs/about.md, docs/installation/docker/without-compose.md, docs/installation/upgrading.md
Instead of docker registry paths looking like `swri-robotics/bag-database/bag-database:tag` they now just look like `swri-robotics/bag-database:tag`.
=> Simplifying docker registry paths
